### PR TITLE
feat(seo): add noindex robots meta for premium articles

### PR DESCRIPTION
**Pull request by keithamus**
This stops google indexing premium articles - effectively disabling the "first click free" for premium content

Redo of #1425 but inside FT org so the build works 😄

### CODE REVIEW

**Comment by andygnewman** [comment]
To respond to @matthew-andrews question on slack.

For the controller we do have tests https://github.com/Financial-Times/next-article/blob/master/test/server/controllers/article.test.js

Whilst currently these are limited to the main features, it would be good to increase the coverage level (https://coveralls.io/github/Financial-Times/next-article) with any new features added.

**Comment by matthew-andrews** [comment]
for reference, here was my question:-
https://financialtimes.slack.com/archives/ft-next-stream-stream/p1465286390000018

**Comment by keithamus** [comment]
Tests added.

**Comment by matthew-andrews** [comment]
this looks good to me, would one of @bjfletcher or @andygnewman mind giving this a +1/-1?

**Comment by bjfletcher** [comment]
:+1:

**Comment by matthew-andrews** [comment]
@keithamus over to you 😄

**Pull request merged**
