### PR TITLE
Use `srcset` and `sizes` rather than <picture />

### PR DESCRIPTION
**Pull request by ironsidevsquincy**
Also tidy the main image sizes

### CODE REVIEW

**Comment by andygnewman** [comment]
Looks OK, but wonder why you've changed the image sizes of 320 and 480 to 300 and 500? Whilst they may look more convenient, the 320 and 480 related to explicit use cases on the site.

**Comment by ironsidevsquincy** [comment]
As far as I can see they're not used - `M`: 700, `L`: 620, `XL`: 680. Anything smaller is full width of the viewport, so these sizes seemed to cover a wide range

**Comment by andygnewman** [comment]
Sorry, should have said that they related to more-ons, though usage may have changed.

**Comment by ironsidevsquincy** [comment]
Might have got it wrong, but thought the code in `article-pod-mapping-v3.js` related to the more ons. Just removed the 470px width image from that, as no images are shown on smaller breakpoints

**Comment by andygnewman** [comment]
Yeah, sorry was getting my srcsets and sizes confused. 👍

**Comment by ironsidevsquincy** [comment]
ha, yeah, the terminology is all a bit ambiguous/confusing

**Pull request merged**
