### PR TITLE
New header styles

### PR DESCRIPTION
**Pull request by keirog**
(Genre styling coming next)

### CODE REVIEW

**Comment by keirog** [comment]
Before (mobile) | After (mobile)
--- | ---
mobile-before | mobile-after

Before (desktop):
desktop-before

After (desktop):
desktop-after

**Comment by next-team** [comment]
I've spotted a [difference](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/article/2015-06-30/10:00-2272/failures/index.html) between your pull request and production — [see full output](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/article/2015-06-30/10:00-2272/successes/index.html)

**Comment by matthew-andrews** [comment]
:+1:  nice image diffing ;)

**Comment by matthew-andrews** [comment]
i particularly like the topics mentions

**Comment by keirog** [comment]
yep, I really like the new design. next up, genre styling!

**Pull request merged**
