### PR TITLE
Pass XSLT errors on to Sentry

### PR DESCRIPTION
**Pull request by phamann**
In an attempt to diagnose: https://app.getsentry.com/nextftcom/ft-next-article/group/75681439/

/cc @adambraimbridge

### CODE REVIEW

**Comment by adambraimbridge** [comment]
:+1:

**Comment by adambraimbridge** [comment]
@phamann I vote we keep this, even if it was only for debugging

**Comment by ironsidevsquincy** [comment]
merge or close

**Comment by matthew-andrews** [comment]
there are a lot of xslt errors  :+1: merge

**Comment by ironsidevsquincy** [comment]
MERGGGGGEEEEEEEEEEE

**Pull request merged**
