### PR TITLE
Use nTypeAlpha(3) for all breakpoints

### PR DESCRIPTION
**Pull request by keirog**
See [next-type issue 22](https://github.com/Financial-Times/next-type/issues/22)

### CODE REVIEW

**Comment by keirog** [comment]
Before
before

After
after

**Comment by matthew-andrews** [comment]
looking forward to the image diff picking this up :grin:

**Comment by matthew-andrews** [comment]
the ie10 thing that killed the pr build should be improved by a pr i just merged

**Comment by keirog** [comment]
@matthew-andrews ta!

**Pull request merged**
