### PR TITLE
use correct article title in sharing

### PR DESCRIPTION
**Pull request by andygnewman**
article title in share template was out of date vs what's returned by v3

### CODE REVIEW

**Comment by matthew-andrews** [comment]
does it need to be `encodeURIComponent`'d?

**Comment by matthew-andrews** [comment]
i think we should have a helper for that if so ^^

**Comment by andygnewman** [comment]
You're right, does need encoding, so sorting that out now.

**Comment by matthew-andrews** [comment]
ahh, sorry…  i think you can do this more simply with `{{#encode title}}` in the template ^^
https://github.com/Financial-Times/n-handlebars/blob/master/src/helpers/encode.js

**Comment by matthew-andrews** [comment]
or maybe it's `{{#encode}}{{title}}{{/encode}}`

**Comment by andygnewman** [comment]
Good point, it's actually {{encode title mode='uriComponent'}}

**Pull request merged**
