### PR TITLE
feat(amp): add amphtml link to metadata block

### PR DESCRIPTION
**Pull request by keithamus**
I've hardcoded the amp.ft.com url; it seems to be the convention. If you'd rather I can change it to use a config/env var.

(Redo of #1424 but inside FT org so the build works 😄)

### CODE REVIEW

**Comment by matthew-andrews** [comment]
nice, does this look OK? @georgecrawford / @quarterto ?

**Comment by quarterto** [comment]
lgtm!

**Comment by georgecrawford** [comment]
me2

**Comment by keithamus** [comment]
Had to rebase, but code is the same.

**Pull request merged**
