### PR TITLE
Fix unclickable links on bb7

### PR DESCRIPTION
**Pull request by adgad**
/cc @i-like-robots @andygnewman @matthew-andrews 
Currently all article links (inc. share, save, in-article links) are not clickable on BB7 devices. Adding a clearfix fixes that ¯\_(ツ)_/¯

### CODE REVIEW

**Comment by matthew-andrews** [comment]
hmm… if we fix this in `n-layout` would it fix it globally?  also gonna need a comment ……

`{{! handlebars comment probably best so it doesn't get into the output}}`

**Comment by matthew-andrews** [comment]
also, any idea *why*?

**Comment by adgad** [comment]
Yeah hold off for now...I'm still digging into the rabbit hole

**Comment by matthew-andrews** [comment]
:rabbit2:

**Comment by adgad** [comment]
Traced it down to this: https://github.com/Financial-Times/o-grid/pull/116

**Pull request closed without merging**
