### PR TITLE
Separate build-production out into its own step

### PR DESCRIPTION
**Pull request by matthew-andrews**

### CODE REVIEW

**Comment by adambraimbridge** [comment]
@matthew-andrews Was this PR to do with debugging CircleCI, or do you want to keep it? In the latter case, how is build-production now triggered? (Out of curiosity)

**Comment by matthew-andrews** [comment]
@adambraimbridge this is the difference between `app` and `appLegacy` in the config vars

http://git.svc.ft.com:8080/projects/NEXTPRIVATE/repos/config-vars/browse/models/continuous-integration/app.js#27

**Comment by matthew-andrews** [comment]
want to keep this…… don't know why this isn't working :/

**Comment by imranolas** [comment]
Green build :) Is this ok to merge?

**Comment by matthew-andrews** [comment]
yup

**Pull request merged**
