### PR TITLE
Move event to use o-tracking

### PR DESCRIPTION
**Pull request by tom-parker**
cc @adambraimbridge

### CODE REVIEW

**Comment by adambraimbridge** [comment]
:+1:  I'm not completely familiar with the o-tracking side of this, but the PR looks good.

**Comment by tom-parker** [comment]
Basically we just fire these ```oTracking.event``` custom events. o-tacking will then pick these up and fire them to spoor appropriately.

**Comment by adambraimbridge** [comment]
<nods head> Looks good to me, cheers

**Comment by imranolas** [comment]
:+1: it this ready to merge?

**Pull request merged**
