### PR TITLE
Tidy up transforming

### PR DESCRIPTION
**Pull request by ironsidevsquincy**
For now, just makes the transform chain more sane - https://github.com/Financial-Times/next-article/blob/transform-tidy/server/transforms/body.js#L42-L57

This might become moot once we move over to XSLT, but might be able to keep the same transforming style

cc: @i-like-robots

### CODE REVIEW

**Comment by matthew-andrews** [comment]
@ironsidevsquincy @i-like-robots you might like to add some image diff captures for some of the things we're currently transforming so we can visually check the refactors are having no impact :)

**Comment by matthew-andrews** [comment]
https://github.com/Financial-Times/next-article/blob/master/test/visual/test.js#L20-26

**Comment by ironsidevsquincy** [comment]
good idea. I'll add some tests for the components

**Comment by matthew-andrews** [comment]
just to warn you — images typically don't work well…… I might need to add some logic to hide images.  poke me if this causes you pain and i'll make that tweak

**Comment by ironsidevsquincy** [comment]
should be fine without images. why don't they work? because the image diff uses compressed images to compare?

**Comment by matthew-andrews** [comment]
i don't know… i haven't had a chance to debug it yet :smile: … if you'd like to look into it, would be great :-)

**Pull request merged**
