### PR TITLE
Defer requiring of modules untill after bootstrap

### PR DESCRIPTION
**Pull request by ironsidevsquincy**
i.e. after polys are filled - should fix e.g. https://app.getsentry.com/nextftcom/ft-next-frontend/group/74032974/

### CODE REVIEW

**Comment by adgad** [comment]
Is that particular error just Edge not being polyfilled correctly?

**Comment by ironsidevsquincy** [comment]
Well that error's on Chrome 42.0, which I hope should be able to be polyfilled

**Comment by adgad** [comment]
For some weird reason, that's Edge's UA string - https://msdn.microsoft.com/en-us/library/hh869301(v=vs.85).aspx

Polyfill service gives nothing for that UA: https://cdn.polyfill.io/v1/polyfill.js?ua=Mozilla/5.0%20(Windows%20NT%2010.0;%20Win64;%20x64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/42.0.2311.135%20Safari/537.36%20Edge/12.10240

I'm guessing sentry reads the UA slightly differently...

**Comment by adgad** [comment]
This is the weird/interesting reason: http://blogs.windows.com/msedgedev/2015/06/17/building-a-more-interoperable-web-with-microsoft-edge/

I'll raise an issue on polyfill service

**Comment by ironsidevsquincy** [comment]
woah

**Pull request merged**
