### PR TITLE
Update styling for V1 article content warning

### PR DESCRIPTION
**Pull request by tom-parker**
screen shot 2015-06-24 at 15 41 47

### CODE REVIEW

**Comment by matthew-andrews** [comment]
Would you mind adding this component to the image diff thing? https://github.com/Financial-Times/next-article/blob/master/test/visual/test.js

**Comment by matthew-andrews** [comment]
aha spaces :)

**Comment by next-team** [comment]
I've spotted a [difference](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/article/2015-06-24/15:12-2156/failures/index.html) between your pull request and production — [see full output](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/article/2015-06-24/15:12-2156/successes/index.html)

**Comment by matthew-andrews** [comment]
thank you @next-team, i think that's what @tom-parker was intending to do :-)

**Pull request merged**
