### PR TITLE
Grid update

### PR DESCRIPTION
**Pull request by adamsilver**

### CODE REVIEW

**Comment by next-team** [comment]
I've spotted a [difference](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/article/2015-07-10/08:32-2580/failures/index.html) between your pull request and production — [see full output](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/article/2015-07-10/08:32-2580/successes/index.html)

**Comment by aintgoin2goa** [comment]
looks like that freaky bot has a point - looks possibly button-related?

**Comment by adamsilver** [comment]
@aintgoin2goa nothing to do with moi - just buttons - not touched those bad boys.

**Comment by adamsilver** [comment]
Oh actually, was forced to update bower dependency - took the blue pill.

**Comment by next-team** [comment]
I've spotted a [difference](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/article/2015-07-10/09:05-2583/failures/index.html) between your pull request and production — [see full output](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/article/2015-07-10/09:05-2583/successes/index.html)

**Comment by adamsilver** [comment]
Yep, the button in live, I have not regressed those buttons @phamann is on the case

**Pull request merged**
