### PR TITLE
removed much legacy

### PR DESCRIPTION
**Pull request by gvonkoss**
@andygnewman @adgad 
seeing as I'm deleting stuff both of you wrote, anyone care to weigh in? :D

### CODE REVIEW

**Comment by adgad** [comment]
Can you also delete the server-side bit that sets `tagToFollow`?

**Comment by andygnewman** [comment]
Presume you've checked with myFT about removing the tag to follow, that was something they built.

Should also get rid of the flag for articleSuggestedRead (not sure if it's used in the server side code to determine whether to run the code for it), but if it's the only show in town, probably no longer required.

Also is there any CSS you can delete?

**Comment by commuterjoy** [comment]
"removed much legacy" sounds like a Trump slogan

**Comment by gvonkoss** [comment]
@andygnewman as far as I can tell, a good bit of the suggestedRead includes read next and such, so best keep that flag for now?

@adgad i've removed all of the server-side code, and what was cropping up in n-concept, as well.

**Comment by andygnewman** [comment]
@gvonkoss the comment about flag removal was more that if read next etc is the only option why have it controlled by flag vs just doing it anyway. The flag originally was for an AB test.

**Comment by adgad** [comment]
LGTM

**Pull request merged**
