### PR TITLE
Catch errors in more ons

### PR DESCRIPTION
**Pull request by ironsidevsquincy**
This endpoint is seriously slow, times out most of the time

### CODE REVIEW

**Comment by matthew-andrews** [comment]
hmm… don't like suppressing all errors blindly.

should be able to do a simple `instanceof` check here…… next-ft-api-client will convert timeouts to not `.ok` responses

**Comment by ironsidevsquincy** [comment]
k, updated to only ignore `ReadTimeoutError`s, though thinking about it, should probably send these to splunk

**Comment by ironsidevsquincy** [comment]
got some splunk logging now

**Comment by matthew-andrews** [comment]
:+1:

**Pull request merged**
