### PR TITLE
Switch nbt branch to one that hopefully works

### PR DESCRIPTION
**Pull request by keirog**

### CODE REVIEW

**Comment by next-team** [comment]
I've spotted a [difference](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/article/2015-06-17/15:07-1999/failures/index.html) between your pull request and production — [see full output](https://s3-eu-west-1.amazonaws.com/ft-next-qa/image_diffs/article/2015-06-17/15:07-1999/successes/index.html)

**Comment by keirog** [comment]
Loving the image diffs!
Getting some errors though:
Error: TypeError: 'undefined' is not a function (evaluating 'this.handleLogEvent.bind(this)')
Error: HIERARCHY_REQUEST_ERR: DOM Exception 3: A Node was inserted somewhere it doesn't belong.
@matthew-andrews Anything thing worry about?

**Comment by matthew-andrews** [comment]
umm @keirog not that one but it shouldn't have flagged this diff :-/

**Comment by keirog** [comment]
@matthew-andrews looks o-date related

**Comment by matthew-andrews** [comment]
:+1:

**Comment by matthew-andrews** [comment]
but i switch javascript off on imaeg diffs :(

**Comment by keirog** [comment]
:see_no_evil:

**Pull request merged**
