### PR TITLE
Stop diluting our Google juice by including ‘rel=canonical’s #SEO

### PR DESCRIPTION
**Pull request by matthew-andrews**
screen shot 2015-12-18 at 14 31 23

### CODE REVIEW

**Comment by commuterjoy** [comment]
+1

... though Google doesn't index us atm?

**Comment by matthew-andrews** [comment]
I don't think it indexes us but it would be able to reach Next stuff if it discovers and tries to follow an old `m.ft.com` URL.

**Comment by commuterjoy** [comment]
yup!

**Comment by matthew-andrews** [comment]
still then, without clearing cookies, it won't be able to get back to that `canonical` URL…  not sure what the consequence of that is… :speak_no_evil:

**Pull request merged**
