### PR TITLE
Use FinancierTextWeb for body text, in serification test

### PR DESCRIPTION
**Pull request by keirog**
…but keep Financier Display for headline

### CODE REVIEW

**Comment by keirog** [comment]
Difficult to show here, but:
Before
before

After
after

**Comment by matthew-andrews** [comment]
Save | Comments a bit funky……

**Comment by keirog** [comment]
Yep, but nothing to do with this change, no?

**Comment by matthew-andrews** [comment]
nope :+1:

**Comment by keirog** [comment]
Ta. (That should change soon anyway, with new button coming in.)

**Pull request merged**
