### PR TITLE
Use signed fetch toggle to switch off DNS resolution for tests

### PR DESCRIPTION
**Pull request by i-like-robots**
cc @matthew-andrews

### CODE REVIEW

**Comment by matthew-andrews** [comment]
:+1: thanks!

**Comment by matthew-andrews** [comment]
Added a commit to hopefully fix the build

**Comment by matthew-andrews** [comment]
Podcasts tests still failing :-/

screen shot 2015-10-20 at 14 02 04

**Comment by i-like-robots** [comment]
kein cache für die grüne!

**Pull request merged**
