### PR TITLE
make sure metadata also returns a content_classification

### PR DESCRIPTION
**Pull request by aintgoin2goa**

### CODE REVIEW

**Comment by matthew-andrews** [comment]
how come?

**Comment by matthew-andrews** [comment]
i only recently changed this:-
https://github.com/Financial-Times/next-article/commit/ae42e37ac58a04e110673e9373b5b4a7ca71e91d

**Comment by matthew-andrews** [comment]
if the idea here is to remove those elements from pages that show barriers i think it would be better to stop them from being requested in the first place than make them error

**Comment by aintgoin2goa** [comment]
it's not about barriers - the Access endpoint expects anything with a uuid to respond to a HEAD request to give a content_classification.  I'm seeing requests to access for these specific endpoints take > 8 seconds.  Presumably cos Access is expecting headers and retries / gets confused.

The other option is to adjust the access_metadata file, but that might end up accidentally making content free

**Comment by matthew-andrews** [comment]
i have another idae

**Comment by aintgoin2goa** [comment]
are you going to share it?

**Comment by matthew-andrews** [comment]
https://github.com/Financial-Times/next-article/pull/536

also it might help to move articles to `/content/uuid` (something i planned to do at some point)

**Pull request closed without merging**
