### PR TITLE
Amend: switch sourcepoint flag off for smoke tests

### PR DESCRIPTION
**Pull request by andygnewman**
Sourcepoint is what we use to identify ad blocking behaviour and uses pixels to test browser response and is expanded in n-ui 5.2.0.
These pixels fail a11y tests.
So this switches the relevant flag off in the a11y tests.

### CODE REVIEW

**Comment by adgad** [comment]
Out of curiosity, what do they fail?

**Comment by andygnewman** [comment]
The dummy pixels are img tags and don't have alts, which is a no-no for accessibility. So just like we turn ads flag off, we need to turn this one off aswell.

**Comment by adgad** [comment]
👍  Worth raising with Sourcepoint as well, and trying to get them to fix.

**Comment by andygnewman** [comment]
Their script does pull the pixels out once the check is complete, but the timing conflicts with the a11y test being run.

**Comment by adgad** [comment]
Ahh gotcha :)

**Pull request merged**
