### PR TITLE
`(--docker)--`

### PR DESCRIPTION
**Pull request by matthew-andrews**

### CODE REVIEW

**Comment by matthew-andrews** [comment]
@andygnewman @i-like-robots 

this wasn't that hard :-)

**Comment by i-like-robots** [comment]
Looks good, surprised Circle doesn't baulk at not having its own XSLT version.

**Comment by matthew-andrews** [comment]
it's still installing a version of xslt……

**Comment by matthew-andrews** [comment]
i don't know why the `circle.yml` change breaks the build now !

**Pull request merged**
