### PR TITLE
Cache for an hour

### PR DESCRIPTION
**Pull request by wheresrhys**
Any reason not to?

### CODE REVIEW

**Comment by matthew-andrews** [comment]
i think we need to implement purging…… otherwise editorial gonna be a bit angry i think

**Comment by matthew-andrews** [comment]
really think we could start off figuring out purge+long cache logic problems in content-classification-api first :]

**Comment by andygnewman** [comment]
What would happen if Editorial update an existing story - does that override the cache?

**Comment by wheresrhys** [comment]
How about we cache for longer if a story is more than 24/48/72 hours long?

**Comment by matthew-andrews** [comment]
@andygnewman no not without us implementing purging, which i don't trust on next.ft.com atm

**Pull request closed without merging**
