### PR TITLE
Fix slightly odd paragraph spacing

### PR DESCRIPTION
**Pull request by andygnewman**
Fixed issue documented here https://github.com/Financial-Times/next-article/issues/510

@matthew-andrews - this is a fix to an issue you raised

Fixed in CSS;
- removing float: left from timestamp to get timestamp within overall container
- reducing timestamp top/bottom margins from 10px to 8px to ensure box is same height as image (56px) when story headline on single line

Before
screen shot 2015-06-26 at 11 45 44

After
screen shot 2015-06-26 at 11 46 07

CLOSED and different PR created for it.

### CODE REVIEW

**Comment by matthew-andrews** [comment]
need to get that other pr pulled in first i think :)

**Comment by andygnewman** [comment]
@matthew-andrews pulled in previous pr

**Comment by matthew-andrews** [comment]
hmm.. I wouldn't normally suggest this but in this one case might be worth doing a little rebase to tidy up the git history.  Let's chat on Monday :)

**Comment by andygnewman** [comment]
CLOSED - horrendous git commit history - replaced with cleaner pr

**Pull request closed without merging**
