### PR TITLE
Notify saucelabs does nothing

### PR DESCRIPTION
**Pull request by matthew-andrews**

### CODE REVIEW

**Comment by ironsidevsquincy** [comment]
Really? This was working, what's changed?

**Comment by matthew-andrews** [comment]
it just always comes up as passed

**Comment by ironsidevsquincy** [comment]
Pretty sure this was working. As I'm on bug duty can take a look

**Comment by ironsidevsquincy** [comment]
Fixed by https://github.com/Financial-Times/next-article/pull/1039

**Pull request closed without merging**
